import { GamesIconImages } from '@components/Images'
const GamesData = [
  {
    image: '',
    name: 'Supercars Underground Racing',
    date: 'June 25, 2021',
    link: 'https://play.google.com/store/apps/details?id=com.rivalwheels.racing.car&pcampaignid=web_share',
    platform: 'Unity',
  },
  {
    image: GamesIconImages.TaxiSim.src.src,
    name: 'Real Taxi Driving : Grand City',
    date: 'Jan 26, 2016',
    link: 'https://play.google.com/store/apps/details?id=com.supersmashact.citytaxidriver3d&pcampaignid=web_share',
    platform: 'Unity',
  },

  {
    image: GamesIconImages.MegaRamp.src.src,
    name: 'Mega Ramps - Crazy Car Stunts',
    date: 'Feb 20, 2022',
    link: 'https://play.google.com/store/apps/details?id=com.mvgames.mega.ramps.extreme.race&pcampaignid=web_share',
    platform: 'Unity',
  },
  {
    image: GamesIconImages.HillDrive.src.src,
    name: 'Truck Simulator: Offroad 4x4',
    date: 'Sep 9, 2021',
    link: 'https://play.google.com/store/apps/details?id=com.rivalwheels.hilldrive&pcampaignid=web_share',
    platform: 'Unity',
  },
  {
    image: GamesIconImages.RealEst.src.src,
    name: 'REAL ESTATE Business Tycoon',
    date: 'Nov 25, 2021',
    link: 'https://play.google.com/store/apps/details?id=com.rivalwheels.realestate.simulation&pcampaignid=web_share',
    platform: 'Unity',
  },
  {
    image: GamesIconImages.Sniper.src.src,
    name: 'Sniper Fury: One Shot Kill',
    date: 'May 21, 2021',
    link: 'https://play.google.com/store/apps/details?id=com.rivalwheels.sniper.shooter&pcampaignid=web_share',
    platform: 'Unity',
  },
  // {
  //   image: '',
  //   name: 'Extreme Bike Stunt 2021: Crazy',
  //   date: 'Sep 28, 2020',
  //   link: 'https://play.google.com/store/apps/details?id=com.rivalwheels.bike.stunt&pcampaignid=web_share',
  //   platform: 'Unity',
  // },
  {
    image: '',
    name: 'Modern Warfare: Gun Games',
    date: 'Mar 9, 2021',
    link: 'https://play.google.com/store/apps/details?id=com.rivalwheels.commando.secret.mission&pcampaignid=web_share',
    platform: 'Unity',
  },
  {
    image: GamesIconImages.Parking.src.src,
    name: 'Amazing Parking Simulator Game',
    date: 'Jul 21, 2021',
    link: 'https://play.google.com/store/apps/details?id=com.rivalwheels.Parking.Simulation&pcampaignid=web_share',
    platform: 'Unity',
  },
  {
    image: '',
    name: 'Parking Jam 3d: Parking Games',
    date: 'Sep 30, 2021',
    link: 'https://play.google.com/store/apps/details?id=com.Rivalwheels.ParkingSimulation.Master&pcampaignid=web_share',
    platform: 'Unity',
  },
  {
    image: GamesIconImages.BusSim.src.src,
    name: 'Bus Simulator : Indonesia City',
    date: 'Mar 16, 2021',
    link: 'https://play.google.com/store/apps/details?id=com.rivalwheels.bussimulator2021&pcampaignid=web_share',
    platform: 'Unity',
  },
  {
    image: '',
    name: 'Flag Runner 3d - World Quiz',
    date: 'Dec 8, 2021',
    link: 'https://play.google.com/store/apps/details?id=com.fungamesstudio.what.is&pcampaignid=web_share',
    platform: 'Unity',
  },
  {
    image: '',
    name: 'Pull the Pin - Pin Puzzle',
    date: 'Aug 17, 2022',
    link: 'https://play.google.com/store/apps/details?id=com.fungamesstudio.pull.the.pin&pcampaignid=web_share',
    platform: 'Unity',
  },
  {
    image: GamesIconImages.ArrowFest.src.src,
    name: 'Arrow Fest: Stickman Archer',
    date: 'Oct 8, 2021',
    link: 'https://play.google.com/store/apps/details?id=com.fungamesstudio.arrow.fest.battle&pcampaignid=web_share',
    platform: 'Unity',
  },
  {
    image: GamesIconImages.LuckyEgg.src.src,
    name: 'Catch Birds Eggs',
    date: 'Oct 23, 2021',
    link: 'https://play.google.com/store/apps/details?id=com.FunGamesStudio.lucky.eggs&pcampaignid=web_share',
    platform: 'Unity',
  },
  // {
  //   image: '',
  //   name: 'Fidget Trading Toys - Pop It',
  //   date: 'Sep 23, 2021',
  //   link: 'https://play.google.com/store/apps/details?id=com.fungamesstudio.fidget.trading.master&pcampaignid=web_share',
  //   platform: 'Unity',
  // },
  {
    image: GamesIconImages.Junkyard.src.src,
    name: 'Junkyard Keeper: Garbage truck',
    date: 'Aug 17, 2022',
    link: 'https://play.google.com/store/apps/details?id=com.fungamesstudio.crane.picker&pcampaignid=web_share',
    platform: 'Unity',
  },
]

export { GamesData }
