const GamesData = [
  {
    image: 'v1694585521/Icons/Game Icons/Racing_Car_bkxocj.jpg',
    name: 'Supercars Underground Racing',
    date: 'June 25, 2021',
    link: 'https://play.google.com/store/apps/details?id=com.rivalwheels.racing.car&pcampaignid=web_share',
    platform: 'Unity',
  },
  {
    image: 'v1694585521/Icons/Game Icons/TaxiSim_eb0wuu.png',
    name: 'Real Taxi Driving : Grand City',
    date: 'Jan 26, 2016',
    link: 'https://play.google.com/store/apps/details?id=com.supersmashact.citytaxidriver3d&pcampaignid=web_share',
    platform: 'Unity',
  },

  {
    image: 'v1694585517/Icons/Game Icons/MegaRamp_sqoc5k.png',
    name: 'Mega Ramps - Crazy Car Stunts',
    date: 'Feb 20, 2022',
    link: 'https://play.google.com/store/apps/details?id=com.mvgames.mega.ramps.extreme.race&pcampaignid=web_share',
    platform: 'Unity',
  },
  {
    image: 'v1694585514/Icons/Game Icons/HillDrive_avtkie.png',
    name: 'Truck Simulator: Offroad 4x4',
    date: 'Sep 9, 2021',
    link: 'https://play.google.com/store/apps/details?id=com.rivalwheels.hilldrive&pcampaignid=web_share',
    platform: 'Unity',
  },
  {
    image: 'v1694585520/Icons/Game Icons/RealEstate_di4pav.png',
    name: 'REAL ESTATE Business Tycoon',
    date: 'Nov 25, 2021',
    link: 'https://play.google.com/store/apps/details?id=com.rivalwheels.realestate.simulation&pcampaignid=web_share',
    platform: 'Unity',
  },
  {
    image: 'v1694585525/Icons/Game Icons/Sniper_z89uud.png',
    name: 'Sniper Fury: One Shot Kill',
    date: 'May 21, 2021',
    link: 'https://play.google.com/store/apps/details?id=com.rivalwheels.sniper.shooter&pcampaignid=web_share',
    platform: 'Unity',
  },
  // {
  //   image: '',
  //   name: 'Extreme Bike Stunt 2021: Crazy',
  //   date: 'Sep 28, 2020',
  //   link: 'https://play.google.com/store/apps/details?id=com.rivalwheels.bike.stunt&pcampaignid=web_share',
  //   platform: 'Unity',
  // },
  {
    image: 'v1694585518/Icons/Game Icons/Modern_Warfare_y49bw3.jpg',
    name: 'Modern Warfare: Gun Games',
    date: 'Mar 9, 2021',
    link: 'https://play.google.com/store/apps/details?id=com.rivalwheels.commando.secret.mission&pcampaignid=web_share',
    platform: 'Unity',
  },
  {
    image: 'v1694585518/Icons/Game Icons/Parking_u8ehjj.png',
    name: 'Amazing Parking Simulator Game',
    date: 'Jul 21, 2021',
    link: 'https://play.google.com/store/apps/details?id=com.rivalwheels.Parking.Simulation&pcampaignid=web_share',
    platform: 'Unity',
  },
  {
    image: 'v1694585510/Icons/Game Icons/Amazing_Parking_zzy0y5.jpg',
    name: 'Parking Jam 3d: Parking Games',
    date: 'Sep 30, 2021',
    link: 'https://play.google.com/store/apps/details?id=com.Rivalwheels.ParkingSimulation.Master&pcampaignid=web_share',
    platform: 'Unity',
  },
  {
    image: 'v1694585513/Icons/Game Icons/BusSimulator_odrfhq.jpg',
    name: 'Bus Simulator : Indonesia City',
    date: 'Mar 16, 2021',
    link: 'https://play.google.com/store/apps/details?id=com.rivalwheels.bussimulator2021&pcampaignid=web_share',
    platform: 'Unity',
  },
  {
    image: 'v1694585514/Icons/Game Icons/Flag_Runner_ty2bwd.jpg',
    name: 'Flag Runner 3d - World Quiz',
    date: 'Dec 8, 2021',
    link: 'https://play.google.com/store/apps/details?id=com.fungamesstudio.what.is&pcampaignid=web_share',
    platform: 'Unity',
  },
  {
    image: 'v1694585517/Icons/Game Icons/Pull_the_Pin_puzpa4.jpg',
    name: 'Pull the Pin - Pin Puzzle',
    date: 'Aug 17, 2022',
    link: 'https://play.google.com/store/apps/details?id=com.fungamesstudio.pull.the.pin&pcampaignid=web_share',
    platform: 'Unity',
  },
  {
    image: 'v1694585509/Icons/Game Icons/ArrowFest_kgykzm.png',
    name: 'Arrow Fest: Stickman Archer',
    date: 'Oct 8, 2021',
    link: 'https://play.google.com/store/apps/details?id=com.fungamesstudio.arrow.fest.battle&pcampaignid=web_share',
    platform: 'Unity',
  },
  {
    image: 'v1694585515/Icons/Game Icons/LuckyEgg_smtjbn.png',
    name: 'Catch Birds Eggs',
    date: 'Oct 23, 2021',
    link: 'https://play.google.com/store/apps/details?id=com.FunGamesStudio.lucky.eggs&pcampaignid=web_share',
    platform: 'Unity',
  },
  // {
  //   image: '',
  //   name: 'Fidget Trading Toys - Pop It',
  //   date: 'Sep 23, 2021',
  //   link: 'https://play.google.com/store/apps/details?id=com.fungamesstudio.fidget.trading.master&pcampaignid=web_share',
  //   platform: 'Unity',
  // },
  {
    image: 'v1694585510/Icons/Game Icons/Junkyard_wirevn.jpg',
    name: 'Junkyard Keeper: Garbage truck',
    date: 'Aug 17, 2022',
    link: 'https://play.google.com/store/apps/details?id=com.fungamesstudio.crane.picker&pcampaignid=web_share',
    platform: 'Unity',
  },
]

export { GamesData }
